name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - requests
  - gdal
  - python-dotenv
  - psycopg2
  - streamlit
  - pip
  - pip:
    - rasterstats
  - geopandas
  - plotly
  - rasterstats
  - leafmap
  - matplotlib
  - schedule
  - time