name: myenv

channels:
  - conda-forge

dependencies:
  - python=3.9
  - gdal
  - geopandas
  - rasterio
  - rasterstats
  - shapely
  - fiona
  - pandas
  - numpy
  - requests
  - python-dotenv
  - psycopg2
  - streamlit
  - plotly
  - leafmap
  - matplotlib
  - schedule
  - pip